### ISSUE TITLE
user referral tracking

### ISSUE THREAD

**Issue by championswimmer** [coding-blocks/oneauth#565]
- [x] signup query refcode #567
- [x] user refferral code generation #566 
- [x] add referredBy field in users #568

**Comment by TdevM** [comment]
this should be closed now.

**Comment by TdevM** [comment]
Feature is now deployed.
